2015/05/11 22:13:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "users".' in C:\xampp\htdocs\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\framework\web\CController.php(270): CController->missingAction('users')
#1 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('users')
#2 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('site/users')
#3 C:\xampp\htdocs\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\seguidor\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/seguidor/index.php?r=site/users
---
2015/05/11 22:13:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "user".' in C:\xampp\htdocs\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\framework\web\CController.php(270): CController->missingAction('user')
#1 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('user')
#2 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('site/user')
#3 C:\xampp\htdocs\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\seguidor\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/seguidor/index.php?r=site/user
---
2015/05/11 22:14:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "user.html".' in C:\xampp\htdocs\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\framework\web\CController.php(270): CController->missingAction('user.html')
#1 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('user.html')
#2 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('site/user.html')
#3 C:\xampp\htdocs\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\seguidor\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/seguidor/index.php?r=site/user.html
---
2015/05/11 22:14:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "user.php".' in C:\xampp\htdocs\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\framework\web\CController.php(270): CController->missingAction('user.php')
#1 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('user.php')
#2 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('site/user.php')
#3 C:\xampp\htdocs\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\seguidor\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/seguidor/index.php?r=site/user.php
---
2015/05/11 22:37:04 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`seguidordb`.`proyecto`, CONSTRAINT `proyecto_ibfk_1` FOREIGN KEY (`manager`) REFERENCES `user` (`iduser`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `proyecto` (`name`, `description`, `begindate`, `enddate`, `manager`, `registrationdate`, `updatedate`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6).
in C:\xampp\htdocs\seguidor\protected\controllers\ProyectoController.php (73)
in C:\xampp\htdocs\seguidor\index.php (13)
2015/05/11 22:37:04 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`seguidordb`.`proyecto`, CONSTRAINT `proyecto_ibfk_1` FOREIGN KEY (`manager`) REFERENCES `user` (`iduser`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `proyecto` (`name`, `description`, `begindate`, `enddate`, `manager`, `registrationdate`, `updatedate`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6)' in C:\xampp\htdocs\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\seguidor\protected\controllers\ProyectoController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\framework\web\actions\CInlineAction.php(49): ProyectoController->actionCreate()
#4 C:\xampp\htdocs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('proyecto/create')
#14 C:\xampp\htdocs\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\seguidor\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/seguidor/index.php?r=proyecto/create
HTTP_REFERER=http://localhost/seguidor/index.php?r=proyecto/create
---
2015/05/11 22:42:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "proe".' in C:\xampp\htdocs\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('proe')
#1 C:\xampp\htdocs\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\seguidor\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/seguidor/index.php?r=proe
---
2015/05/11 22:52:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "comentarios".' in C:\xampp\htdocs\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('comentarios')
#1 C:\xampp\htdocs\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\seguidor\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/seguidor/index.php?r=comentarios
---
2015/05/11 22:56:44 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`seguidordb`.`actividad`, CONSTRAINT `actividad_ibfk_1` FOREIGN KEY (`idproyecto`) REFERENCES `proyecto` (`idproyecto`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `actividad` (`name`, `description`, `begindate`, `enddate`, `registrationdate`, `updatedate`, `idproyecto`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6).
in C:\xampp\htdocs\seguidor\protected\controllers\ActividadController.php (73)
in C:\xampp\htdocs\seguidor\index.php (13)
2015/05/11 22:56:44 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`seguidordb`.`actividad`, CONSTRAINT `actividad_ibfk_1` FOREIGN KEY (`idproyecto`) REFERENCES `proyecto` (`idproyecto`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `actividad` (`name`, `description`, `begindate`, `enddate`, `registrationdate`, `updatedate`, `idproyecto`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6)' in C:\xampp\htdocs\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\seguidor\protected\controllers\ActividadController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\framework\web\actions\CInlineAction.php(49): ActividadController->actionCreate()
#4 C:\xampp\htdocs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('actividad/creat...')
#14 C:\xampp\htdocs\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\seguidor\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/seguidor/index.php?r=actividad/create
HTTP_REFERER=http://localhost/seguidor/index.php?r=actividad/create
---
2015/05/11 22:58:18 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`seguidordb`.`comentario`, CONSTRAINT `comentario_ibfk_1` FOREIGN KEY (`idactividad`) REFERENCES `actividad` (`idactividad`)). The SQL statement executed was: INSERT INTO `comentario` (`name`, `description`, `registrationdate`, `idactividad`) VALUES (:yp0, :yp1, :yp2, :yp3).
in C:\xampp\htdocs\seguidor\protected\controllers\ComentarioController.php (73)
in C:\xampp\htdocs\seguidor\index.php (13)
2015/05/11 22:58:18 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`seguidordb`.`comentario`, CONSTRAINT `comentario_ibfk_1` FOREIGN KEY (`idactividad`) REFERENCES `actividad` (`idactividad`)). The SQL statement executed was: INSERT INTO `comentario` (`name`, `description`, `registrationdate`, `idactividad`) VALUES (:yp0, :yp1, :yp2, :yp3)' in C:\xampp\htdocs\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\seguidor\protected\controllers\ComentarioController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\framework\web\actions\CInlineAction.php(49): ComentarioController->actionCreate()
#4 C:\xampp\htdocs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('comentario/crea...')
#14 C:\xampp\htdocs\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\seguidor\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/seguidor/index.php?r=comentario/create
HTTP_REFERER=http://localhost/seguidor/index.php?r=comentario/create
---
2015/05/12 02:57:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\seguidor\protected\controllers\ComentarioController.php:157
Stack trace:
#0 C:\xampp\htdocs\seguidor\protected\controllers\ComentarioController.php(55): ComentarioController->loadModel('2')
#1 [internal function]: ComentarioController->actionView('2')
#2 C:\xampp\htdocs\framework\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(ComentarioController), Array)
#3 C:\xampp\htdocs\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(ComentarioController), Object(ReflectionMethod), Array)
#4 C:\xampp\htdocs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('view')
#13 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('comentario/view')
#14 C:\xampp\htdocs\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\seguidor\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/seguidor/index.php?r=comentario/view&id=2
---
2015/05/12 02:58:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "load".' in C:\xampp\htdocs\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\framework\web\CController.php(270): CController->missingAction('load')
#1 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('load')
#2 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('comentario/load')
#3 C:\xampp\htdocs\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\seguidor\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/seguidor/index.php?r=comentario/load&id=12
---
2015/05/12 02:58:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\seguidor\protected\controllers\ComentarioController.php:157
Stack trace:
#0 C:\xampp\htdocs\seguidor\protected\controllers\ComentarioController.php(55): ComentarioController->loadModel('2')
#1 [internal function]: ComentarioController->actionView('2')
#2 C:\xampp\htdocs\framework\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(ComentarioController), Array)
#3 C:\xampp\htdocs\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(ComentarioController), Object(ReflectionMethod), Array)
#4 C:\xampp\htdocs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('view')
#13 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('comentario/view')
#14 C:\xampp\htdocs\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\seguidor\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/seguidor/index.php?r=comentario/view&id=2
---
2015/05/12 03:12:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "id=1".' in C:\xampp\htdocs\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\framework\web\CController.php(270): CController->missingAction('id=1')
#1 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('id=1')
#2 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('comentario/id=1')
#3 C:\xampp\htdocs\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\seguidor\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/seguidor/index.php?r=comentario/id=1
---
2015/05/12 03:12:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "comentario?update=1".' in C:\xampp\htdocs\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('comentario?upda...')
#1 C:\xampp\htdocs\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\seguidor\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/seguidor/index.php?r=comentario?update=1
---
2015/05/12 03:13:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "comentario?idactividad=2".' in C:\xampp\htdocs\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('comentario?idac...')
#1 C:\xampp\htdocs\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\seguidor\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/seguidor/index.php?r=comentario?idactividad=2
---
2015/05/12 03:17:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\seguidor\protected\controllers\ComentarioController.php:157
Stack trace:
#0 C:\xampp\htdocs\seguidor\protected\controllers\ComentarioController.php(55): ComentarioController->loadModel('2')
#1 [internal function]: ComentarioController->actionView('2')
#2 C:\xampp\htdocs\framework\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(ComentarioController), Array)
#3 C:\xampp\htdocs\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(ComentarioController), Object(ReflectionMethod), Array)
#4 C:\xampp\htdocs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('view')
#13 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('comentario/view')
#14 C:\xampp\htdocs\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\seguidor\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/seguidor/index.php?r=comentario/view&id=2
---
2015/05/12 18:09:17 [error] [php] Use of undefined constant username - assumed 'username' (C:\xampp\htdocs\seguidor\protected\components\UserIdentity.php:25)
Stack trace:
#0 C:\xampp\htdocs\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#1 C:\xampp\htdocs\framework\base\CModel.php(159): CInlineValidator->validate()
#2 C:\xampp\htdocs\seguidor\protected\controllers\SiteController.php(94): LoginForm->validate()
#3 C:\xampp\htdocs\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 C:\xampp\htdocs\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\seguidor\index.php(13): CWebApplication->run()
REQUEST_URI=/seguidor/index.php?r=site/login
in C:\xampp\htdocs\seguidor\protected\components\UserIdentity.php (25)
in C:\xampp\htdocs\seguidor\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\seguidor\protected\controllers\SiteController.php (94)
2015/05/12 18:09:41 [error] [php] Use of undefined constant username - assumed 'username' (C:\xampp\htdocs\seguidor\protected\components\UserIdentity.php:25)
Stack trace:
#0 C:\xampp\htdocs\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#1 C:\xampp\htdocs\framework\base\CModel.php(159): CInlineValidator->validate()
#2 C:\xampp\htdocs\seguidor\protected\controllers\SiteController.php(94): LoginForm->validate()
#3 C:\xampp\htdocs\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 C:\xampp\htdocs\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\seguidor\index.php(13): CWebApplication->run()
REQUEST_URI=/seguidor/index.php?r=site/login
in C:\xampp\htdocs\seguidor\protected\components\UserIdentity.php (25)
in C:\xampp\htdocs\seguidor\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\seguidor\protected\controllers\SiteController.php (94)
2015/05/12 18:25:18 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'seguidordb.participante' doesn't exist. The SQL statement executed was: SELECT p.* FROM proyecto p,participante t WHERE p.idproyecto = t.idproyecto  AND t.iduser =sebanime02.
in C:\xampp\htdocs\seguidor\protected\controllers\ProyectoController.php (129)
in C:\xampp\htdocs\seguidor\index.php (13)
2015/05/12 18:25:18 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'seguidordb.participante' doesn't exist. The SQL statement executed was: SELECT p.* FROM proyecto p,participante t WHERE p.idproyecto = t.idproyecto  AND t.iduser =sebanime02' in C:\xampp\htdocs\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\seguidor\protected\controllers\ProyectoController.php(129): CDbCommand->queryAll()
#2 C:\xampp\htdocs\framework\web\actions\CInlineAction.php(49): ProyectoController->actionIndex()
#3 C:\xampp\htdocs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\framework\web\filters\CFilter.php(40): CFilterChain->run()
#6 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#10 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('')
#12 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('proyecto')
#13 C:\xampp\htdocs\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 C:\xampp\htdocs\seguidor\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/seguidor/index.php?r=proyecto
HTTP_REFERER=http://localhost/seguidor/index.php?r=site/login
---
2015/05/12 18:25:48 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sebanime02' in 'where clause'. The SQL statement executed was: SELECT p.* FROM proyecto p,user_proyecto t WHERE p.idproyecto = t.idproyecto  AND t.iduser =sebanime02.
in C:\xampp\htdocs\seguidor\protected\controllers\ProyectoController.php (129)
in C:\xampp\htdocs\seguidor\index.php (13)
2015/05/12 18:25:48 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sebanime02' in 'where clause'. The SQL statement executed was: SELECT p.* FROM proyecto p,user_proyecto t WHERE p.idproyecto = t.idproyecto  AND t.iduser =sebanime02' in C:\xampp\htdocs\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\seguidor\protected\controllers\ProyectoController.php(129): CDbCommand->queryAll()
#2 C:\xampp\htdocs\framework\web\actions\CInlineAction.php(49): ProyectoController->actionIndex()
#3 C:\xampp\htdocs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\framework\web\filters\CFilter.php(40): CFilterChain->run()
#6 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#10 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('')
#12 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('proyecto')
#13 C:\xampp\htdocs\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 C:\xampp\htdocs\seguidor\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/seguidor/index.php?r=proyecto
HTTP_REFERER=http://localhost/seguidor/index.php?r=site/login
---
2015/05/12 18:30:11 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.iduser" is not defined.' in C:\xampp\htdocs\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\framework\web\auth\CWebUser.php(146): CComponent->__get('iduser')
#1 C:\xampp\htdocs\seguidor\protected\controllers\ProyectoController.php(126): CWebUser->__get('iduser')
#2 C:\xampp\htdocs\framework\web\actions\CInlineAction.php(49): ProyectoController->actionIndex()
#3 C:\xampp\htdocs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\framework\web\filters\CFilter.php(40): CFilterChain->run()
#6 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#10 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('')
#12 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('proyecto')
#13 C:\xampp\htdocs\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 C:\xampp\htdocs\seguidor\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/seguidor/index.php?r=proyecto
HTTP_REFERER=http://localhost/seguidor/index.php?r=site/login
---
2015/05/13 21:42:18 [error] [exception.CException] exception 'CException' with message 'The property "itemView" cannot be empty.' in C:\xampp\htdocs\framework\zii\widgets\CListView.php:210
Stack trace:
#0 C:\xampp\htdocs\framework\web\CBaseController.php(147): CListView->init()
#1 C:\xampp\htdocs\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#2 C:\xampp\htdocs\seguidor\protected\views\proyecto\index.php(28): CBaseController->widget('zii.widgets.CLi...', Array)
#3 C:\xampp\htdocs\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#6 C:\xampp\htdocs\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#7 C:\xampp\htdocs\seguidor\protected\controllers\ProyectoController.php(134): CController->render('index', Array)
#8 C:\xampp\htdocs\framework\web\actions\CInlineAction.php(49): ProyectoController->actionIndex()
#9 C:\xampp\htdocs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\framework\web\filters\CFilter.php(40): CFilterChain->run()
#12 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#14 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#15 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#16 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('')
#18 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('proyecto')
#19 C:\xampp\htdocs\framework\base\CApplication.php(184): CWebApplication->processRequest()
#20 C:\xampp\htdocs\seguidor\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/seguidor/index.php?r=proyecto
HTTP_REFERER=http://localhost/seguidor/index.php?r=site/login
---
2015/05/13 23:38:01 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`seguidordb`.`proyecto`, CONSTRAINT `proyecto_ibfk_1` FOREIGN KEY (`manager`) REFERENCES `user` (`iduser`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `proyecto` (`name`, `description`, `begindate`, `enddate`, `registrationdate`, `updatedate`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5).
in C:\xampp\htdocs\seguidor\protected\controllers\ProyectoController.php (73)
in C:\xampp\htdocs\seguidor\index.php (13)
2015/05/13 23:38:01 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`seguidordb`.`proyecto`, CONSTRAINT `proyecto_ibfk_1` FOREIGN KEY (`manager`) REFERENCES `user` (`iduser`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `proyecto` (`name`, `description`, `begindate`, `enddate`, `registrationdate`, `updatedate`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5)' in C:\xampp\htdocs\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\seguidor\protected\controllers\ProyectoController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\framework\web\actions\CInlineAction.php(49): ProyectoController->actionCreate()
#4 C:\xampp\htdocs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('proyecto/create')
#14 C:\xampp\htdocs\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\seguidor\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/seguidor/index.php?r=proyecto/create
HTTP_REFERER=http://localhost/seguidor/index.php?r=proyecto/create
---
2015/05/13 23:38:40 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`seguidordb`.`proyecto`, CONSTRAINT `proyecto_ibfk_1` FOREIGN KEY (`manager`) REFERENCES `user` (`iduser`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `proyecto` (`name`, `description`, `begindate`, `enddate`, `registrationdate`, `updatedate`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5).
in C:\xampp\htdocs\seguidor\protected\controllers\ProyectoController.php (73)
in C:\xampp\htdocs\seguidor\index.php (13)
2015/05/13 23:38:40 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`seguidordb`.`proyecto`, CONSTRAINT `proyecto_ibfk_1` FOREIGN KEY (`manager`) REFERENCES `user` (`iduser`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `proyecto` (`name`, `description`, `begindate`, `enddate`, `registrationdate`, `updatedate`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5)' in C:\xampp\htdocs\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\seguidor\protected\controllers\ProyectoController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\framework\web\actions\CInlineAction.php(49): ProyectoController->actionCreate()
#4 C:\xampp\htdocs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\framework\web\CWebApplication.php(141): CWebApplication->runController('proyecto/create')
#14 C:\xampp\htdocs\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\seguidor\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/seguidor/index.php?r=proyecto/create
HTTP_REFERER=http://localhost/seguidor/index.php?r=proyecto/create
---
